### ISSUE TITLE
submodule commit missing

### ISSUE THREAD

**Issue by csmart** [shakenfist/deploy#44]
The latest `deploy` code appears to be pointing to a `shakenfist` commit that doesn't exist (https://github.com/shakenfist/shakenfist/tree/a25a7923b7e54951ff84bf75d48d0fa6e83b696e). Not sure which commit you want that to be? Should it be a tagged release by default? Or is master used as dev and not always expected to work and people should be checking out the latest tag for the `deploy` repo?

```
$ git submodule update 
fatal: remote error: upload-pack: not our ref a25a7923b7e54951ff84bf75d48d0fa6e83b696e
Fetched in submodule path 'shakenfist', but it did not contain a25a7923b7e54951ff84bf75d48d0fa6e83b696e. Direct fetching of that commit failed.
```

Latest commit in deploy master:
```
commit 1dd31600e9bc96ad0cdbd2e567d316c1b6fba8d4 (HEAD -> master, origin/master, origin/HEAD)
Merge: f954892 50fbba8
Author: Andy McCallum <andy@mandoon.com>
Date:   Fri Jul 31 09:21:09 2020 +1000

    Merge pull request #41 from shakenfist/ci-fixes
    
    CI fixes
```

**Comment by csmart** [comment]
Oh never mind.. you fixed it.

**Comment by mikalstill** [comment]
Yeah, I think this is an artefact of submodules and how I do cherry picks to stable at the moment... I need to rethink how this works.

That said, the submodule isn't even used for pypi installs...
