### ISSUE TITLE
Use the ubuntu cloud archive to get more modern libvirt / qemu

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/deploy#49]

**Comment by mandoonandy** [comment]
Would moving to Ubuntu 20.04 solve this?

**Comment by mikalstill** [comment]
So 20.04 would give us more modern stuff now, but not in four years... Cloud archive is how you get modern hypervisor things into LTS releases. That said, I regret using cloud archive on 18.04 because it put the machines into a state I don't really love (broken python3 dependancies for packages not used by OpenStack for example). So maybe we should just always use the latest LTS or something?

**Comment by mandoonandy** [comment]
I think so. At least move to the latest LTS today since it avoids some issues ie. the final push to python3 in Ubuntu.
Latest LTS does seem reasonable. Maybe not strict policy to use to the latest LTS - an "aspirational goal"?

**Comment by mikalstill** [comment]
I no longer thing cloud archive is a good idea.
