### ISSUE TITLE
Submodule

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/deploy#54]
The submodule copy of shakenfist adds extra steps for first time users and annoys me during development.

I suggest that it be removed - thus removing two installation steps. In place, the playbook will git clone and checkout the requested tag/branch in the same directory (with a .gitignore directive for that directory). Also add an option for developers to specify a path to a local copy.

Yes nods?

**Comment by mikalstill** [comment]
That seems reasonable. Perhaps something with the release variable like:

* vX.Y.Z -- install that version from pypi
* git -- install git master
* git:branch -- install a specific git branch

Or is the middle one redundant?

**Comment by mandoonandy** [comment]
Looks excellent.
I'd like a fourth option, to point the deployer at a local copy - a common dev scenario.

**Comment by mikalstill** [comment]
I kind of need this at the moment so I am going to have a go.
